### PR TITLE
[#157952284] Fix endpoint reference for folders

### PR DESCRIPTION
**Pull request by dianaclarke**
See:

- https://www.pivotaltracker.com/story/show/157952284

### CODE REVIEW

**Comment by nealrichardson** [comment]
I don't really speak .rst so I defer to someone who knows better.

**Comment by dianaclarke** [comment]
Lol, me neither. But if you fetch the branch and `make html` you can verify. Here's a screenshot of it working locally for me now.

screen shot 2018-05-30 at 3 00 14 pm

**Comment by dianaclarke** [comment]
Lol, me neither. But if you fetch the branch and `make html` you can verify. Here's a screenshot of it working locally for me now.

screen shot 2018-05-30 at 3 00 14 pm

**Review by nealrichardson — APPROVED** [review]
LGTM

**Pull request merged**
